#!/bin/bash
export CLANG_PREBUILT_BIN=/clang11/bin
export LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN_a=/GCC/aarch64-linux-android/bin
export LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN_b=/GCC/arm-linux-androideabi-4.9/bin
export LD_LIBRARY_PATH=/clang11/lib64:$$LD_LIBRARY_PATH
export PATH=${CLANG_PREBUILT_BIN}:${LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN_a}:${LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN_b}:$PATH
export ARCH=arm64
export CLANG_TRIPLE=aarch64-linux-gnu-
export CROSS_COMPILE=aarch64-linux-androidkernel-
export CROSS_COMPILE_COMPAT=arm-linux-androidkernel-
export CC=clang
make ARCH=arm64 CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-androidkernel- CROSS_COMPILE_COMPAT=arm-linux-androidkernel- CC=clang O=out vendor/kona_defconfig

make -j24 ARCH=arm64 CLANG_TRIPLE=aarch64-linux-gnu- DTB_EXT=dtc CROSS_COMPILE=aarch64-linux-androidkernel- CROSS_COMPILE_COMPAT=arm-linux-androidkernel- CC=clang O=out 

